### ISSUE TITLE
is execTransactions meant to resolve right after user confirmed tx?

### ISSUE THREAD

**Issue by mikheevm** [gnosis/contract-proxy-kit#10]
Is execTransactions meant to resolve right after user confirmed tx? Is there a way to subscribe to transactions execution? As a dapp developer, I'd like to (for example, re-fetching the data after tx confirmed instead of polling)

**Comment by cag** [comment]
execTransactions resolves when the transaction hash becomes available. There's the possibility of subscribing to the execution via promievents if using web3.js or the TransactionResult object if using ethers.js, but if WalletConnected to a Safe, the only that that you would get back is the hash. I think there might be a way to get a TransactionResult object that will let you wait if using ethers.js from the hash, but I actually don't know, and I think there's not really a way to construct a promievent if using web3 in that scenario.
