### ISSUE TITLE
Gas limit estimations far too high

### ISSUE THREAD

**Issue by KadenZipfel** [gnosis/contract-proxy-kit#101]
At Omen, users have been consistently reporting the gas limit being much higher than necessary, seemingly randomly (see https://github.com/protofire/omen-exchange/issues/1033). Considering we use the CPK to execute transactions, I figure there must either be something going on with the CPK or maybe Metamask. Any ideas on what might be causing this issue?

**Comment by cag** [comment]
This appears on both MetaMask and Authereum, and my working hypothesis in the past was that it could be due to rate-limiting feature on INFURA or something.
