### ISSUE TITLE
Allow counterfactual contract deployment.

### ISSUE THREAD

**Issue by Georgi87** [gnosis/contract-proxy-kit#13]
Use case:
To allow non-web3 wallets (no in-app browser or wallet connect) to participate in Dapps, it is required to allow all interaction including approvals of tokens without asking the user to send transactions. In addition, this change also requires the user to sign only one transaction, the approval transaction for the proxy contract can be cut. This functionality can be implemented by asking the user to send tokens to a counterfactual contract address and deploying the contract with a relayer service, which can be reimbursed from the contract account (like we do it for the Safe app).

**Comment by rmeissner** [comment]
will be handled in #67
