### ISSUE TITLE
Allow salt nonce to be configured

### ISSUE THREAD

**Issue by cag** [gnosis/contract-proxy-kit#14]
`create2` takes a salt parameter when it is used. Since the executor of this opcode is the factory, the way authorization of counterfactual proxies happen is by hashing the address of the creator into the salt. An additional nonce, specifiable by the creator, is hashed into the salt. This salt nonce is currently predetermined, but may be passed in as a parameter to generate new proxies for which the owner controls.

**Comment by viraj124** [comment]
Hi Guys, we need to have multiple proxies enabled for a user for ETHOnline can this be worked on ?
