### ISSUE TITLE
[Discord] overflow error when sending 50$ of Wei

### ISSUE THREAD

**Issue by sche** [gnosis/contract-proxy-kit#146]
Reported issue https://discordapp.com/channels/477106835862716416/477391201708802058/812475211869323295 

Hi there, I'm getting an overflow error when using contract-proxy-kit. I'm sending a very reasonable amount of wei as the value parameter, equal to $50 USD, but contract-proxy-kit seems to be trying to force the value param to fit inside of a Number causing an overflow: https://github.com/gnosis/contract-proxy-kit/blob/v2.1.0/src/utils/transactions.ts#L72

it seems the error comes from value >= MAX_SAFE inside bignumber.js

**Comment by germartinez** [comment]
This is a known issue. The fix will be included in the new release on monday.

**Comment by NotRealAI** [comment]
> This is a known issue. The fix will be included in the new release on monday.

Thank you for all your hard work
