### ISSUE TITLE
Add documentation for salt nonce

### ISSUE THREAD

**Issue by rmeissner** [gnosis/contract-proxy-kit#17]
It would be good to explicitly state what our default salt nonce. Also it should be explained how the address of the Safe is calculated based on this salt nonce and the initial owner.

**Comment by cag** [comment]
I know you're probably busy right now, but I wrote some docs about this. Dunno if I should reiterate the `create2` formula in the docs, or if what was written is enough.

I get the feeling that this will be changed up a bit anyway when we figure out a strategy on how to deal with #38 and #26
