### ISSUE TITLE
Proper Safe integration

### ISSUE THREAD

**Issue by cag** [gnosis/contract-proxy-kit#2]
At least two things:

- [x] How to do custom RPC call for batch transactions
- [x] Best way to detect if web3.js/ethers.js connected to a Safe

**Comment by cag** [comment]
@rmeissner May I have the specs for the custom JSON-RPC that would allow me to do a multisend?

@germartinez @mikheevm @DmitryBespalov  Do you happen to know the best way to detect if a provider is the Gnosis Safe?

**Comment by germartinez** [comment]
Hi @cag,
You can have a look at this to see how we identify the provider https://github.com/gnosis/safe-react/blob/5583c9420b99b5cc2856f00dae335748a2fc6380/src/logic/wallets/getWeb3.js#L81

**Comment by cag** [comment]
Would there be a way to detect that WalletConnect (https://github.com/gnosis/safe-react/blob/5583c9420b99b5cc2856f00dae335748a2fc6380/src/logic/wallets/getWeb3.js#L118) is connecting to a Safe?

**Comment by mikheevm** [comment]
@cag sorry, do you mean if you want to detect if wallet connected via walletconnect is a Safe? If yes, then you should be able to get the name of the wallet in `providerObject.currentProvider.wc.peerMeta`

**Comment by cag** [comment]
Awesome, I think that should do it.

**Comment by DmitryBespalov** [comment]
`gs_multi_send(Subtransaction, …)` - Rpc method is `gs_multi_send` and takes an array of Subtransaction objects. 

Object | Subtransaction |   |  
-- | -- | -- | --
Field | Type | Required | Description
to | String | Yes | Must not be a zero address. Hex address. Example value:`"0xc50554e3b5702dcb395992a57c21ea8676bc1a7d"`
value | String | No | Either a base-10 integer or up to 256-bit hex value. Default is 0 (if not present). Example values:`"10000000000000", "0x2dcb3", "0x0", "0"`
data | String | No | Hex value. Default is empty (0-byte data)
operation | Int | No | `0` – ‘call’ (default), `1` – ‘delegate call’. Only `0` is allowed for now.

Prohibited transactions:
- `operation` is `delegateCall` or
- `to` is safe address and `data` is not empty.

Example JSON RPC:

```
{
    "id": 12374,
    "jsonrpc": "2.0",
    "method": "gs_multi_send",
    "params": [
      {
        "to": "0x05c85Ab5B09Eb8A55020d72daf6091E04e264af9",
        "value": "10000" // send eth
      },
      {
        "to": "0x05c85Ab5B09Eb8A55020d72daf6091E04e264af9",
        "value": "0x0123",
        "data": "0x0123456",
        "operation": 0
      },
      {
        "to": "0xb3a4Bc89d8517E0e2C9B66703d09D3029ffa1e6d",
        // erc-20 transfer
        "data": "0xa9059cbb00000000000000000000000046F228b5eFD19Be20952152c549ee478Bf1bf36b0000000000000000000000000000000000000000000000000000000000000000"
      }
    ]
  }
```

**Comment by rmeissner** [comment]
For the `to` field it can obviously be `0x0`, but it must not be `null` (@DmitryBespalov `Must not be a zero address.` is not true ;) )

**Comment by DmitryBespalov** [comment]
@rmeissner updated, thanks! 😄

**Comment by cag** [comment]
Awesome, thanks a bunch y'all!

I believe this is all that's needed to start writing code for this task, so it's just a matter of deciding to do it now.

**Comment by cag** [comment]
@rmeissner @germartinez If I'm not mistaken, the Gnosis Safe Authenticator injected Web3 provider does not have a custom way to access the `gs_multi_send` call right? In that scenario, I guess only the WalletConnect integration would work as is, if I'm not mistaken. Are there plans to add that feature?

**Comment by rmeissner** [comment]
This is not planned
