### ISSUE TITLE
Change in generated proxy address between 1.1.0 and 1.1.1

### ISSUE THREAD

**Issue by cag** [gnosis/contract-proxy-kit#26]
This is due to the switch in the master copy used: #24 

This needs to be documented, and perhaps somehow easily targeted for backwards compatibility reasons. Ideally, there would be a way of future-proofing the deterministic proxy address.

**Comment by germartinez** [comment]
Related to https://github.com/gnosis/contract-proxy-kit/issues/38

**Comment by rmeissner** [comment]
I will add this to the next project, since we should handle this (or add some logic for it)

**Comment by cag** [comment]
I'd say this is sort of a duplicate of #38
