### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by denisgranha** [gnosis/contract-proxy-kit#44]
I would expect some of the logic to be clearly stated in one of the first paragraphs, something like:

1. Creation of contract is not performed in https://github.com/gnosis/contract-proxy-kit#cpkcreate but in the later execTransaction function.
2. Address of the CPK can be known before hand by calling cpk.create and cpk.address
3. Address of the CPK is deterministic and only dependent on the wallet address used to sign the transactions, the owner.

Keep up the good job guys :clap:

**Comment by cag** [comment]
Hey Denis, I've written some of this stuff higher up in the docs under the [CPK.create](https://github.com/gnosis/contract-proxy-kit#cpkcreate) section. Hopefully that resolves the issues listed in your comment, but if not, feel free to reopen this issue. Thanks for your kind words!
