### ISSUE TITLE
Estimated gas limit doesn't work for rinkeby

### ISSUE THREAD

**Issue by mikheevm** [gnosis/contract-proxy-kit#7]
Esimated gas limit (https://github.com/gnosis/contract-proxy-kit/blob/master/src/index.js#L306) doesn't work for rinkeby because of some rinkeby features (@rmeissner explained me) causing the transaction to be stuck

**Comment by cag** [comment]
Used http://green-summer.surge.sh/ with MM connected to Rinkeby. I wasn't able to repro this, even though https://rinkeby.etherscan.io/tx/0x9563a8c639f2b3e212c105ddac9044302fc2037c61dd106f3ab93161788daab5 was successful.

**Comment by rmeissner** [comment]
No but this highly depends on the state of rinkeby (https://stats.rinkeby.io/) if other transactions are pending the bigger ones get dropped (I also ran into this issue multiple times). I do not see the point in setting it to the block gas limit. We should implement a decent estimation as bloggaslimit is also not really feasible on mainnet.
