### ISSUE TITLE
Export Web3Adapter

### ISSUE THREAD

**Issue by marcovc** [gnosis/contract-proxy-kit#77]
Hi,

I can't find Web3Adapter on my npm installation of contract-proxy-kit. Since the README mentions it I guess the packaging is leaving it out by mistake?

**Comment by germartinez** [comment]
Hello @marcovc,

Are you using the last published CPK version (v1.1.1)? `Web3Adapter` is not public yet.

If you are using v1.1.1, notice that the README file in master branch has this warning:

**Warning:** This documentation is for the 2.x series development version of the contract proxy kit.
For documentation on the current stable 1.x series, go [here](https://github.com/gnosis/contract-proxy-kit/tree/v1.1.1#contract-proxy-kit).

**Comment by marcovc** [comment]
Oops I overlooked it, thanks!
