### ISSUE TITLE
Use new implementation of the Safe contract (v1.2.0) after the bug bounty period

### ISSUE THREAD

**Issue by germartinez** [gnosis/contract-proxy-kit#86]
Use new implementation of the Safe contract (v1.2.0) after the bug bounty period.

https://github.com/gnosis/safe-contracts/releases/tag/v1.2.0

0x6851D6fDFAfD08c0295C392436245E5bc78B0185

**Comment by emilianobonassi** [comment]
Any ETA for this?

**Comment by germartinez** [comment]
It's available on `v3.0.0`
