### ISSUE TITLE
ethers transactionResponse object

### ISSUE THREAD

**Issue by gitpusha** [gnosis/contract-proxy-kit#88]
Hi, 

When using the cpk the ethers transactionResponse obj seems to be modified and looks like this:

![image](https://user-images.githubusercontent.com/36712489/89122933-b8acbf80-d4cb-11ea-9b41-95e327d49db6.png)

So the TransactionResponse is itself inserted into an Object with the only other property thereof being the `hash` property. But this already exists on the TransactionResponse object. 

It makes the syntax a bit unnecessarily cumbersome:

```javascript
const txResponse = await cpk.execTransactions(..
await txResponse.transactionResponse.wait();
```

instead of plain 
`await txResponse.wait()`

**Comment by germartinez** [comment]
This will be implemented instead: https://github.com/gnosis/contract-proxy-kit/issues/118
